=== sbeesabathuni/XML-XQUERY/WOCO.xsd
<!--CSE532  Project 3-->
<!--File name:  WOCO.xsd-->
<!--Author: Sravya Beesabathuni (111327265 )-->
<!--Brief description: Schema definition of the XML-->
<!-- I pledge my honor that all parts of this project were done by me alone and
without collaboration with anybody else. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="root" type="wocoType"/>
  	<xs:complexType name="wocoType">
	    <xs:sequence>
		      <xs:element ref="Person" maxOccurs="unbounded"/>
		      <xs:element ref="Company" maxOccurs="unbounded"/>
	    </xs:sequence>
  	</xs:complexType>
	<xs:element name="Owner" type="ownerType"/>
	<xs:complexType name="ownerType">
		<xs:sequence>
			<xs:element name="Id" type="xs:integer"/>
			<xs:element name="Name" type="xs:string"/>
			<xs:element name="OwnsCompany" type="companyOwnedType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>	
	<xs:complexType name="companyOwnedType">
		<xs:sequence>
			<xs:element name="CId" type="xs:integer"/>
			<xs:element name="SharesOwned" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Person" type="ownerType"/>
	<xs:element name="Company" type="companyType"/>
	<xs:complexType name="companyType">
		<xs:complexContent>
			<xs:extension base="ownerType">
				<xs:sequence>
					<xs:element name="SharesIssued" type="xs:integer"/>
					<xs:element name="SharePrice" type="xs:decimal"/>
					<xs:element name="Industry" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
					<xs:element name="BoardMember" type="xs:integer" minOccurs="1" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>	
</xs:schema>

=== sbeesabathuni/XML-XQUERY/WOCO.xml
<!--CSE532  Project 3-->
<!--File name:  WOCO.xml-->
<!--Author: Sravya Beesabathuni (111327265 )-->
<!--Brief description: XML file with all the elements having the data entries-->
<!-- I pledge my honor that all parts of this project were done by me alone and
without collaboration with anybody else. -->
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="WOCO.xsd">
	<Person>
		<Id>111</Id>
		<Name>Bill Doe</Name>
		<OwnsCompany>
			<CId>6</CId>
			<SharesOwned>30000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>4</CId>
			<SharesOwned>100000</SharesOwned>
		</OwnsCompany>
	</Person>
	<Person>
		<Id>112</Id>
		<Name>Bill Seth</Name>
		<OwnsCompany>
			<CId>3</CId>
			<SharesOwned>20000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>8</CId>
			<SharesOwned>40000</SharesOwned>
		</OwnsCompany>
	</Person>
	<Person>
		<Id>113</Id>
		<Name>John Smyth</Name>
		<OwnsCompany>
			<CId>1</CId>
			<SharesOwned>20000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>2</CId>
			<SharesOwned>20000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>6</CId>
			<SharesOwned>800000</SharesOwned>
		</OwnsCompany>
	</Person>
	<Person>
		<Id>114</Id>
		<Name>Anne Smyle</Name>
		<OwnsCompany>
			<CId>2</CId>
			<SharesOwned>30000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>5</CId>
			<SharesOwned>500000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>6</CId>
			<SharesOwned>40000</SharesOwned>
		</OwnsCompany>
	</Person>
	<Person>
		<Id>115</Id>
		<Name>Steve Lamp</Name>
		<OwnsCompany>
			<CId>1</CId>
			<SharesOwned>50000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>2</CId>
			<SharesOwned>70000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>7</CId>
			<SharesOwned>50000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>4</CId>
			<SharesOwned>90000</SharesOwned>
		</OwnsCompany>
	</Person>
	<Person>
		<Id>116</Id>
		<Name>May Serge</Name>
		<OwnsCompany>
			<CId>2</CId>
			<SharesOwned>40000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>5</CId>
			<SharesOwned>500000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>4</CId>
			<SharesOwned>-10000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>9</CId>
			<SharesOwned>-40000</SharesOwned>
		</OwnsCompany>
	</Person>
	<Person>
		<Id>117</Id>
		<Name>Bill Public</Name>
		<OwnsCompany>
			<CId>1</CId>
			<SharesOwned>30000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>2</CId>
			<SharesOwned>-9000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>3</CId>
			<SharesOwned>30000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>6</CId>
			<SharesOwned>300000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>8</CId>
			<SharesOwned>80000</SharesOwned>
		</OwnsCompany>
	</Person>
	<Person>
		<Id>118</Id>
		<Name>Muck Lain</Name>
		<OwnsCompany>
			<CId>2</CId>
			<SharesOwned>60000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>7</CId>
			<SharesOwned>-40000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>4</CId>
			<SharesOwned>30000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>9</CId>
			<SharesOwned>-80000</SharesOwned>
		</OwnsCompany>
	</Person>
	<Company>
		<Id>1</Id>
		<Name>QUE</Name>
		<OwnsCompany>
			<CId>2</CId>
			<SharesOwned>10000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>3</CId>
			<SharesOwned>20000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>4</CId>
			<SharesOwned>30000</SharesOwned>
		</OwnsCompany>
		<SharesIssued>150000</SharesIssued>
		<SharePrice>30</SharePrice>
		<Industry>Software</Industry>
		<Industry>Accounting</Industry>
		<BoardMember>113</BoardMember>
		<BoardMember>111</BoardMember>
		<BoardMember>114</BoardMember>
	</Company>
	<Company>
		<Id>2</Id>
		<Name>RHC</Name>
		<SharesIssued>250000</SharesIssued>
		<SharePrice>20</SharePrice>
		<Industry>Accounting</Industry>
		<BoardMember>112</BoardMember>
		<BoardMember>111</BoardMember>
		<BoardMember>115</BoardMember>
	</Company>
	<Company>
		<Id>3</Id>
		<Name>Elgog</Name>
		<OwnsCompany>
			<CId>7</CId>
			<SharesOwned>5000</SharesOwned>
		</OwnsCompany>
		<SharesIssued>1000000</SharesIssued>
		<SharePrice>400</SharePrice>
		<Industry>Software</Industry>
		<Industry>Search</Industry>
		<BoardMember>116</BoardMember>
		<BoardMember>115</BoardMember>
		<BoardMember>117</BoardMember>
	</Company>
	<Company>
		<Id>4</Id>
		<Name>Elpa</Name>
		<OwnsCompany>
			<CId>6</CId>
			<SharesOwned>20000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>3</CId>
			<SharesOwned>30000</SharesOwned>
		</OwnsCompany>
		<SharesIssued>9000000</SharesIssued>
		<SharePrice>300</SharePrice>
		<Industry>Software</Industry>
		<Industry>Hardware</Industry>
		<BoardMember>112</BoardMember>
		<BoardMember>113</BoardMember>
		<BoardMember>118</BoardMember>
	</Company>
	<Company>
		<Id>5</Id>
		<Name>Alf</Name>
		<OwnsCompany>
			<CId>9</CId>
			<SharesOwned>-100000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>3</CId>
			<SharesOwned>400000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>4</CId>
			<SharesOwned>100000</SharesOwned>
		</OwnsCompany>
		<SharesIssued>10000000</SharesIssued>
		<SharePrice>700</SharePrice>
		<Industry>Software</Industry>
		<Industry>Automotive</Industry>
		<BoardMember>116</BoardMember>
		<BoardMember>111</BoardMember>
		<BoardMember>117</BoardMember>
	</Company>
	<Company>
		<Id>6</Id>
		<Name>Tfos</Name>
		<OwnsCompany>
			<CId>7</CId>
			<SharesOwned>30000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>8</CId>
			<SharesOwned>50000</SharesOwned>
		</OwnsCompany>
		<OwnsCompany>
			<CId>1</CId>
			<SharesOwned>200000</SharesOwned>
		</OwnsCompany>
		<SharesIssued>10000000</SharesIssued>
		<SharePrice>300</SharePrice>
		<Industry>Software</Industry>
		<Industry>Hardware</Industry>
		<BoardMember>112</BoardMember>
		<BoardMember>115</BoardMember>
		<BoardMember>114</BoardMember>
	</Company>
	<Company>
		<Id>7</Id>
		<Name>Ohay</Name>
		<SharesIssued>180000</SharesIssued>
		<SharePrice>50</SharePrice>
		<Industry>Search</Industry>
		<BoardMember>112</BoardMember>
		<BoardMember>118</BoardMember>
		<BoardMember>114</BoardMember>
	</Company>
	<Company>
		<Id>8</Id>
		<Name>Gnow</Name>
		<SharesIssued>150000</SharesIssued>
		<SharePrice>300</SharePrice>
		<Industry>Search</Industry>
		<BoardMember>112</BoardMember>
		<BoardMember>113</BoardMember>
		<BoardMember>114</BoardMember>
	</Company>
	<Company>
		<Id>9</Id>
		<Name>Ydex</Name>
		<SharesIssued>5000000</SharesIssued>
		<SharePrice>100</SharePrice>
		<Industry>Software</Industry>
		<Industry>Search</Industry>
		<BoardMember>113</BoardMember>
		<BoardMember>116</BoardMember>
		<BoardMember>118</BoardMember>
	</Company>	
	
</root>
